import os
import streamlit as st
from groq import Groq
from fpdf import FPDF
import re

st.set_page_config(page_title="AI Research Agent", page_icon="🔬", layout="wide")

st.title("🔬 AI Research Agent")
st.caption("Multi-agent research system powered by LLaMA 3.3 70B via Groq")

with st.sidebar:
    st.header("⚙️ Settings")
    api_key = st.text_input("Groq API Key", type="password", placeholder="gsk_...")
    st.markdown("Get a free key at [console.groq.com](https://console.groq.com)")
    st.divider()
    st.markdown("**How it works**")
    st.markdown("1. 🧠 Planner breaks topic into questions")
    st.markdown("2. 🔍 Researcher answers each question")
    st.markdown("3. 💡 Analyst extracts key insights")
    st.markdown("4. ✍️ Writer composes final report")
    st.divider()
    st.markdown("Built by [SimhasGit](https://github.com/SimhasGit)")

def clean_text(text: str) -> str:
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = text.encode('latin-1', 'replace').decode('latin-1')
    return text

def generate_pdf(topic: str, report: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_left_margin(25)
    pdf.set_right_margin(25)
    pdf.set_top_margin(25)
    pdf.set_auto_page_break(auto=True, margin=25)
    w = pdf.w - 50

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(w, 10, clean_text(topic), align="C")
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(130, 130, 130)
    pdf.cell(w, 6, "Generated by AI Research Agent", align="C")
    pdf.ln(10)

    for line in report.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(2)
        elif line.startswith("# "):
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(w, 8, clean_text(line.replace("# ", "")))
            pdf.ln(2)
        elif line.startswith("## "):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(60, 60, 180)
            pdf.multi_cell(w, 7, clean_text(line.replace("## ", "")))
            pdf.ln(1)
        elif line.startswith("- ") or line.startswith("* "):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(w, 6, clean_text("  - " + line[2:]))
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(w, 6, clean_text(line))

    return bytes(pdf.output())

topic = st.text_input("Enter research topic", placeholder="e.g. AI agents in clinical research")

if st.button("🚀 Start Research", use_container_width=True, type="primary"):
    if not api_key:
        st.error("Please enter your Groq API key in the sidebar")
    elif not topic:
        st.error("Please enter a research topic")
    else:
        client = Groq(api_key=api_key)

        def call_groq(system: str, user: str) -> str:
            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": user}
                ]
            )
            return response.choices[0].message.content.strip()

        col1, col2 = st.columns([1, 2])

        with col1:
            st.subheader("🔄 Agent Progress")
            step1 = st.status("Planner agent...", expanded=False)
            step2 = st.status("Research agent...", expanded=False)
            step3 = st.status("Analyst agent...", expanded=False)
            step4 = st.status("Writer agent...", expanded=False)

        with col2:
            st.subheader("📋 Research Report")
            report_box = st.empty()

        with step1:
            questions = call_groq(
                "You are a research planner.",
                f"Break this into 4 key research questions: {topic}\nReturn only the 4 questions, numbered."
            )
            st.markdown(questions)
            step1.update(label="✅ Planner agent", state="complete")

        with step2:
            findings = call_groq(
                "You are an expert researcher.",
                f"Answer each question thoroughly:\n{questions}"
            )
            st.markdown(findings)
            step2.update(label="✅ Research agent", state="complete")

        with step3:
            insights = call_groq(
                "You are a senior analyst.",
                f"Identify 3 key insights from this research about {topic}:\n{findings}"
            )
            st.markdown(insights)
            step3.update(label="✅ Analyst agent", state="complete")

        with step4:
            report = call_groq(
                "You are an expert report writer.",
                f"""Write a professional report on: {topic}

Research: {findings}
Insights: {insights}

Format:
# {topic}
## Executive Summary
## Key Findings
## Key Insights
## Conclusion"""
            )
            step4.update(label="✅ Writer agent", state="complete")

        report_box.markdown(report)
        st.divider()
        col_md, col_pdf = st.columns(2)

        with col_md:
            st.download_button(
                "⬇️ Download Markdown",
                data=report,
                file_name=f"{topic.replace(' ', '_')}_report.md",
                mime="text/markdown",
                use_container_width=True
            )
        with col_pdf:
            pdf_bytes = generate_pdf(topic, report)
            st.download_button(
                "⬇️ Download PDF",
                data=pdf_bytes,
                file_name=f"{topic.replace(' ', '_')}_report.pdf",
                mime="application/pdf",
                use_container_width=True
            )
